#ifndef DEBUG_BLE_BLE_DATAFORMAT_H_
#define DEBUG_BLE_BLE_DATAFORMAT_H_


typedef enum
{
    BLE_FRAME_TYPE_TEST_REQ             = 0x3132,
	BLE_FRAME_TYPE_TEST_RESP            = 0x3131,

	BLE_FRAME_TYPE_DEV_STATUS_REQ       = 0x3332,
	BLE_FRAME_TYPE_DEV_STATUS_RESP      = 0x3331,

/* Device mode frames */
	BLE_FRAME_TYPE_SET_MODE_NO_SAVE_REQ = 0x3230,
	BLE_FRAME_TYPE_GET_MODE_RESP        = 0x3231,
	BLE_FRAME_TYPE_GET_MODE_REQ			= 0x3232,
	BLE_FRAME_TYPE_SET_MODE_SAVE_REQ	= 0x3234,

/* Indication and auto-settings frames */
	BLE_FRAME_TYPE_SET_INDICATION_AUTOSET_REQ	= 0x3530,
	BLE_FRAME_TYPE_GET_INDICATION_AUTOSET_REQ	= 0x3532,
	BLE_FRAME_TYPE_GET_INDICATION_AUTOSET_RESP	= 0x3531,

	BLE_FRAME_TYPE_GET_PARAM_REQ	= 0x1601,

} BLE_FrameType_TypeDef;


#endif /* DEBUG_BLE_BLE_DATAFORMAT_H_ */
